import numpy as np
from typing import List, Dict, Tuple
from .data_structures import Atom, Bond, Angle, Protein, Residue

PDB_TWO_LETTER_ELEMENTS = {
    'BR','CL','NA','MG','AL','SI','CA','SC','TI','CR','MN','FE','CO','NI','CU','ZN','GA','GE','AS','SE',
    'AG','CD','IN','SN','SB','TE','XE','CS','BA','LA','CE','PR','ND','SM','EU','GD','TB','DY','HO','ER',
    'TM','YB','LU','HF','TA','RE','OS','IR','PT','AU','HG','PB','SR','KR','LI','BE','NE','AR','RU','RH',
    'PD'
}

def _pdb_element_from_atom(atom: Atom) -> str:
    """
    Derive a reasonable element field for a PDB record using atom type/name heuristics.
    """
    source = ''.join([c for c in atom.type if c.isalpha()]) or ''.join([c for c in atom.name if c.isalpha()])
    if not source:
        return '  '
    source = source.upper()
    if len(source) >= 2 and source[:2] in PDB_TWO_LETTER_ELEMENTS:
        element = source[:2]
    else:
        element = source[0]
    return element.rjust(2)

def read_pdb_ca(filename: str) -> List[Tuple[str, str, int, np.ndarray]]:
    """
    Reads C-alpha atoms from PDB.
    Returns list of (res_name, chain, res_num, coords).
    """
    ca_atoms = []
    with open(filename, 'r') as f:
        for line in f:
            if line.startswith('ATOM') and line[12:16].strip() == 'CA':
                res_name = line[17:20].strip()
                chain = line[21]
                res_num = int(line[22:26])
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                ca_atoms.append((res_name, chain, res_num, np.array([x, y, z])))
    return ca_atoms

def read_hdd(filename: str) -> Protein:
    """
    Parses the Hdd topology file generated by remo.py.
    """
    protein = Protein()
    
    with open(filename, 'r') as f:
        lines = f.readlines()
        
    header = lines[0].split()
    natom = int(header[0])
    nang = int(header[1])
    nhbond = int(header[2])
    
    current_line = 1
    
    # Read Atoms
    for _ in range(natom):
        line = lines[current_line].strip()
        current_line += 1
        parts = line.split()
        # Format: idx name type res charge vdwE vdwR hb_da
        idx = int(parts[0])
        name = parts[1]
        atype = parts[2]
        res = parts[3]
        charge = float(parts[4])
        vdwE = float(parts[5])
        vdwR = float(parts[6])
        hb_da = int(parts[7])
        
        atom = Atom(idx, name, atype, res, charge, vdwE, vdwR, hb_da)
        protein.atoms.append(atom)
        
    # Read Bonds
    # FAMRcomm defines bonds for each atom.
    # Hdd has 'natom' bond lines?
    # Let's check remo.py. Yes, it writes generated_bonds corresponding to generated_atoms.
    for _ in range(natom):
        line = lines[current_line].strip()
        current_line += 1
        parts = line.split()
        # Format: idx c1 c2 c3 c4 p1...p8 nbond
        idx = int(parts[0])
        c = [int(parts[1]), int(parts[2]), int(parts[3]), int(parts[4])]
        params = [float(x) for x in parts[5:13]]
        # nbond is last
        
        bond = Bond(idx, c, params)
        protein.bonds_data.append(bond)
        
        # Populate connectivity in Atom objects
        # Bond indices are 1-based atom indices. 
        # But wait, c[i] might be 0 (no bond).
        # Also c[i] points to neighbor.
        atom = protein.get_atom(idx)
        if atom:
            for neighbor_idx in c:
                if neighbor_idx > 0:
                    neighbor = protein.get_atom(neighbor_idx)
                    if neighbor:
                        atom.bonds.append(neighbor)
                        
    # Read Angles
    for _ in range(nang):
        line = lines[current_line].strip()
        current_line += 1
        parts = line.split()
        # Format: idx a1 a2 a3 k theta0 kubo rubo
        # Note: Hdd from remo.py writes: idx a1 a2 a3 p0 p1 p2 p3
        idx = int(parts[0])
        a1 = int(parts[1])
        a2 = int(parts[2])
        a3 = int(parts[3])
        params = [float(x) for x in parts[4:]]
        
        angle = Angle(a1, a2, a3, params[0], params[1], params[2], params[3])
        protein.angles_data.append(angle)
        
    # Read HBonds
    # Hdd has 'nhbond' lines (actually nhbond from header, which was len-1 in remo.py).
    # remo.py writes len(comm_data['hbonds'])-1 lines.
    # Then a comment line?
    # Let's just read until we hit the RAM comment or end.
    # But we know nhbond count.
    
    for _ in range(nhbond):
        if current_line >= len(lines): break
        line = lines[current_line].rstrip()
        current_line += 1
        protein.hbonds_data.append(line)
        
    # Read RAM
    # Remaining lines
    while current_line < len(lines):
        line = lines[current_line].rstrip()
        current_line += 1
        protein.ram_data.append(line)
        
    # Organize into Residues
    # We identify residue starts by backbone Nitrogen atoms
    res_starts = []
    for i, atom in enumerate(protein.atoms):
        # N: Standard backbone
        # NH3: N-terminus (non-PRO)
        # NP: PRO backbone (or N-term PRO)
        if atom.name in ['N', 'NH3', 'NP']:
            res_starts.append(i)
            
    if not res_starts and protein.atoms:
        # Fallback if no N found (unlikely)
        res_starts.append(0)
            
    for k in range(len(res_starts)):
        start = res_starts[k]
        end = res_starts[k+1]-1 if k+1 < len(res_starts) else len(protein.atoms)-1
        
        # Create Residue
        res_name = protein.atoms[start].res_name
        res_num = k + 1
        
        res = Residue(res_num, res_name, start, end)
        for idx in range(start, end + 1):
            res.atoms.append(protein.atoms[idx])
        protein.residues.append(res)
        
    return protein

def write_pdb(protein: Protein, filename: str):
    """
    Writes the protein to a PDB file.
    """
    with open(filename, 'w') as f:
        serial = 1
        for res in protein.residues:
            for atom in res.atoms:
                # ATOM  {serial:5d} {name:^4s} {res:3s} {chain:1s}{resnum:4d}    {x:8.3f}{y:8.3f}{z:8.3f}{occ:6.2f}{bfac:6.2f}          {elem:>2s}
                name = atom.name.strip()
                # Fix name spacing for PDB
                # 4 chars: " CA ", "N   ", " OH "
                if len(name) == 1: pdb_name = f" {name}  "
                elif len(name) == 2: pdb_name = f" {name} "
                elif len(name) == 3:
                    if name[0].isdigit(): pdb_name = f"{name} " # 1H
                    else: pdb_name = f" {name}" # CA
                else: pdb_name = name
                
                chain_id = res.chain_id if getattr(res, 'chain_id', None) else 'A'
                resnum = res.orig_resnum if getattr(res, 'orig_resnum', None) is not None else res.id

                element = _pdb_element_from_atom(atom)

                f.write(f"ATOM  {serial:5d} {pdb_name:4s} {res.name:3s} {chain_id:1s}{resnum:4d}    "
                        f"{atom.coords[0]:8.3f}{atom.coords[1]:8.3f}{atom.coords[2]:8.3f}"
                        f"  1.00  0.00          {element:>2s}\n")
                serial += 1
                if serial > 99999: serial = 1 # Wrap around (simplified)
        f.write("END\n")
